"""relationship to hn_id

Revision ID: 2a63f2441797
Revises: 2e952aa9ba74
Create Date: 2020-09-17 17:03:37.865164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a63f2441797"
down_revision = "2e952aa9ba74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "hacker_news_new_story", ["hn_id"])
    op.drop_constraint(
        "hacker_news_new_story_comment_parent_fkey",
        "hacker_news_new_story_comment",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "hacker_news_new_story_comment",
        "hacker_news_new_story",
        ["parent"],
        ["hn_id"],
    )
    op.create_unique_constraint(None, "hacker_news_top_story", ["hn_id"])
    op.drop_constraint(
        "hacker_news_top_story_comment_parent_fkey",
        "hacker_news_top_story_comment",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "hacker_news_top_story_comment",
        "hacker_news_top_story",
        ["parent"],
        ["hn_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "hacker_news_top_story_comment", type_="foreignkey"
    )
    op.create_foreign_key(
        "hacker_news_top_story_comment_parent_fkey",
        "hacker_news_top_story_comment",
        "hacker_news_top_story",
        ["parent"],
        ["id"],
    )
    op.drop_constraint(None, "hacker_news_top_story", type_="unique")
    op.drop_constraint(
        None, "hacker_news_new_story_comment", type_="foreignkey"
    )
    op.create_foreign_key(
        "hacker_news_new_story_comment_parent_fkey",
        "hacker_news_new_story_comment",
        "hacker_news_new_story",
        ["parent"],
        ["id"],
    )
    op.drop_constraint(None, "hacker_news_new_story", type_="unique")
    # ### end Alembic commands ###
