"""hn tables with hn_id

Revision ID: 2e952aa9ba74
Revises: 2f49a231605f
Create Date: 2020-09-14 18:27:51.068732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e952aa9ba74"
down_revision = "2f49a231605f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hacker_news_new_story",
        sa.Column("hn_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "hacker_news_top_story",
        sa.Column("hn_id", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hacker_news_top_story", "hn_id")
    op.drop_column("hacker_news_new_story", "hn_id")
    # ### end Alembic commands ###
