"""hn_newstory_comments add hn_id column

Revision ID: 2f49a231605f
Revises: c4ee4c9d1958
Create Date: 2020-09-14 07:50:13.319936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f49a231605f"
down_revision = "c4ee4c9d1958"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hacker_news_new_story_comment",
        sa.Column("hn_id", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hacker_news_new_story_comment", "hn_id")
    # ### end Alembic commands ###
