"""hn top story comment hn_id column

Revision ID: c4ee4c9d1958
Revises: d389734b977d
Create Date: 2020-09-11 12:39:51.718335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c4ee4c9d1958"
down_revision = "d389734b977d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hacker_news_top_story_comment",
        sa.Column("hn_id", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hacker_news_top_story_comment", "hn_id")
    # ### end Alembic commands ###
