"""create tables hacker_news

Revision ID: d389734b977d
Revises: 
Create Date: 2020-08-03 13:32:35.701633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d389734b977d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hacker_news_new_story",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("by", sa.String(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("dead", sa.Boolean(), nullable=True),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("poll", sa.Integer(), nullable=True),
        sa.Column("kids", sa.JSON(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("parts", sa.JSON(), nullable=True),
        sa.Column("descendants", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("parsed_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hacker_news_top_story",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("by", sa.String(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("dead", sa.Boolean(), nullable=True),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("poll", sa.Integer(), nullable=True),
        sa.Column("kids", sa.JSON(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("parts", sa.JSON(), nullable=True),
        sa.Column("descendants", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("parsed_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hacker_news_new_story_comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("by", sa.String(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("dead", sa.Boolean(), nullable=True),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("poll", sa.Integer(), nullable=True),
        sa.Column("kids", sa.JSON(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("parts", sa.JSON(), nullable=True),
        sa.Column("descendants", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("parsed_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["parent"], ["hacker_news_new_story.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hacker_news_top_story_comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("by", sa.String(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("dead", sa.Boolean(), nullable=True),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("poll", sa.Integer(), nullable=True),
        sa.Column("kids", sa.JSON(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("parts", sa.JSON(), nullable=True),
        sa.Column("descendants", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("parsed_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["parent"], ["hacker_news_top_story.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hacker_news_top_story_comment")
    op.drop_table("hacker_news_new_story_comment")
    op.drop_table("hacker_news_top_story")
    op.drop_table("hacker_news_new_story")
    # ### end Alembic commands ###
