"""hn_top\new comments updated_time column

Revision ID: e36f87c2b225
Revises: 2a63f2441797
Create Date: 2020-09-21 20:12:42.855709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e36f87c2b225"
down_revision = "2a63f2441797"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hacker_news_new_story_comment",
        sa.Column("updated_time", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "hacker_news_top_story_comment",
        sa.Column("updated_time", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hacker_news_top_story_comment", "updated_time")
    op.drop_column("hacker_news_new_story_comment", "updated_time")
    # ### end Alembic commands ###
