"""flask_backend init tables

Revision ID: 19040462bb9b
Revises: 
Create Date: 2020-08-25 16:12:00.737661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19040462bb9b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_news_story",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("by", sa.String(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("dead", sa.Boolean(), nullable=True),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("poll", sa.Integer(), nullable=True),
        sa.Column("kids", sa.JSON(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("parts", sa.JSON(), nullable=True),
        sa.Column("descendants", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "blog_news_story_comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("by", sa.String(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("dead", sa.Boolean(), nullable=True),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("poll", sa.Integer(), nullable=True),
        sa.Column("kids", sa.JSON(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("parts", sa.JSON(), nullable=True),
        sa.Column("descendants", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["parent"], ["blog_news_story.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("user_uuid", sa.String(length=128), nullable=True),
        sa.Column("email_address", sa.String(length=128), nullable=False),
        sa.Column("is_activated", sa.Boolean(), nullable=True),
        sa.Column("origin", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_uuid"),
    )
    op.create_index(
        op.f("ix_users_email_address"), "users", ["email_address"], unique=True
    )
    op.create_index(
        op.f("ix_users_username"), "users", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email_address"), table_name="users")
    op.drop_table("users")
    op.drop_table("blog_news_story_comment")
    op.drop_table("blog_news_story")
    # ### end Alembic commands ###
