"""id>item_id

Revision ID: a37c24a58e7e
Revises: 5d6f887455e6
Create Date: 2020-08-03 11:08:32.307473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a37c24a58e7e"
down_revision = "5d6f887455e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blog_news_stories", "id", new_column_name="item_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blog_news_stories", "item_id", new_column_name="id")
    # ### end Alembic commands ###
